<?php
declare(strict_types=1);

require_once __DIR__.'/../app/Database.php';
require_once __DIR__.'/../app/PayrollCalculator.php';

function pdfStrings(string $file): array {
    $bytes=file_get_contents($file); if($bytes===false) throw new RuntimeException("No se pudo leer el PDF");
    $pages=[];$pos=0;
    while(($filter=strpos($bytes,'/Filter/FlateDecode',$pos))!==false){$stream=strpos($bytes,"stream\n",$filter);if($stream===false)break;$start=$stream+7;$end=strpos($bytes,'endstream',$start);if($end===false)break;$pos=$end+9;$raw=substr($bytes,$start,$end-$start);if(str_starts_with($raw,"\r"))$raw=substr($raw,1);$decoded=@gzuncompress($raw);if($decoded===false)$decoded=@gzinflate(substr($raw,2));if($decoded===false)continue;preg_match_all('/\(((?:\\.|[^)])*)\)\s*Tj/s',$decoded,$m);$page=[];foreach($m[1] as $v){$v=str_replace(['\\(', '\\)', '\\\\', "\\n", "\\r"],['(',')','\\',' ',' '],$v);$page[]=trim($v);}if($page)$pages[]=$page;}
    return $pages;
}
function money(?string $v): ?int {if($v===null||!preg_match('/^-?[0-9][0-9.]*$/',trim($v)))return null;return (int)str_replace('.','',trim($v));}
function nextValue(array $t,string $label,int $from=0): ?int {foreach($t as $i=>$x){if($i<$from||stripos($x,$label)===false)continue;for($j=$i+1;$j<count($t)&&$j<=$i+4;$j++)if(($n=money($t[$j]))!==null)return $n;}return null;}
function keyRut(string $r): string{return strtoupper(preg_replace('/[^0-9Kk]/','',$r));}
function rows(string $file): array {
    $out=[];foreach(pdfStrings($file) as $t){$idx=null;$rut='';foreach($t as $i=>$x)if(preg_match('/\d{1,3}(?:\.\d{3})+-[0-9Kk]/',$x,$m)&&keyRut($m[0])!=='762712776'){$rut=$m[0];$idx=$i;break;}if(!$rut)continue;$find=['Sueldo base'=>'base','HORAS EXTRA 50%'=>'ot','GRATIFICACION LEGAL'=>'grat','VIATICOS'=>'viaticos','MOVILIZACION'=>'movilizacion','COLACION'=>'colacion','TOTAL IMPONIBLE'=>'taxable','TOTAL NO IMPONIBLE'=>'nonTax','PREVISION'=>'prevision','SALUD'=>'health','TOTAL DESC. LEGALES'=>'legal','TOTAL OTROS DESC.'=>'other','TOTAL HABERES:'=>'haberes','TOTAL DESCUENTOS:'=>'discounts','ALCANCE LIQUIDO:'=>'net'];$r=['rut'=>$rut,'name'=>$t[$idx+1]??''];foreach($find as $label=>$k)$r[$k]=nextValue($t,$label,$idx);$r['afp']='EXT_'.keyRut($rut);$r['health_institution']=in_array('FONASA',$t,true)?'Fonasa':'Isapre';$out[]=$r;}return $out;
}

$pdf=$argv[1]??'';if(!$pdf||!is_file($pdf)){fwrite(STDERR,"Uso: php tools/import_external_for_validation.php liquidaciones.pdf\n");exit(2);}
$items=rows($pdf);$pdo=Database::connection();$pdo->beginTransaction();
try {
    $company=$pdo->query("SELECT id FROM companies ORDER BY id LIMIT 1")->fetchColumn();if(!$company)throw new RuntimeException('No existe una empresa local');$company=(int)$company;
    $pdo->prepare("UPDATE companies SET name=?,rut=?,giro=? WHERE id=?")->execute(['COMERCIALIZADORA Y MAESTRANZA PEDREROS Y BADILLA','76.271.277-6','Empresa externa para validaciÃ³n',$company]);
    $pdo->prepare('DELETE FROM employees WHERE company_id=?')->execute([$company]);$pdo->prepare('DELETE FROM parameter_versions WHERE company_id=?')->execute([$company]);$pdo->prepare('DELETE FROM payroll_periods WHERE company_id=?')->execute([$company]);
    $params=['uf'=>34500,'utm'=>66714,'minimum_wage'=>500000,'afp_cap_uf'=>81.6,'unemployment_cap_uf'=>122.4,'health_cap'=>166320,'mutual'=>.009,'sis'=>.0153,'sc_worker'=>.006,'sc_employer_indefinite'=>.024,'sc_employer_fixed'=>.03,'sanna'=>.0003,'reform_afp'=>.001,'reform_ssp'=>.009,'family_allowance'=>15000,'afp_rates'=>[],'tax_brackets'=>[[0,941638,0,0],[941639,2092530,.04,37666],[2092531,3487550,.08,121367],[3487551,4882570,.135,313182],[4882571,6277590,.23,777026],[6277591,8370120,.304,1241568],[8370121,21622810,.35,1626593],[21622811,999999999,.4,2707733]]];
    foreach($items as $r){$params['afp_rates'][$r['afp']]=($r['taxable']??0)>0?($r['prevision']??0)/$r['taxable']:0;}
    $pdo->prepare('INSERT INTO payroll_periods(company_id,period) VALUES(?,?)')->execute([$company,'2026-07']);$periodId=(int)$pdo->lastInsertId();$json=json_encode($params,JSON_UNESCAPED_UNICODE);$pdo->prepare('INSERT INTO parameter_versions(company_id,period,values_json) VALUES(?,?,?)')->execute([$company,'2026-07',$json]);
    $ins=$pdo->prepare('INSERT INTO employees(company_id,rut,full_name,position,base_salary,contract_type,gratification_type,health_institution,isapre_plan_uf,afp,meal_allowance,transport_allowance,family_loads,mutual_rate,contributes_afp,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?)');$var=$pdo->prepare('INSERT INTO payroll_variables(period_id,employee_id,overtime_50,guaranteed_gratification,non_taxable_bonus,company_loan) VALUES(?,?,?,?,?,?)');$slip=$pdo->prepare('INSERT INTO payslips(period_id,employee_id,calculation_json) VALUES(?,?,?)');$calc=new PayrollCalculator();
    foreach($items as $r){$tax=(int)($r['taxable']??0);$ot=(int)($r['ot']??0);$base=(int)($r['base']??0);$hours=$base>0&&$ot>0?$ot*182/($base*1.5):0;$health=(int)($r['health']??0);$isapre=$r['health_institution']==='Isapre';$ins->execute([$company,$r['rut'],$r['name'],'Trabajador',$base,'Plazo Fijo','Garantizada',$r['health_institution'],$isapre?$health/$params['uf']:0,$r['afp'],(int)($r['colacion']??0),(int)($r['movilizacion']??0),0,.009,'Activo']);$eid=(int)$pdo->lastInsertId();$var->execute([$periodId,$eid,$hours,(int)($r['grat']??0),max(0,(int)($r['nonTax']??0)-(int)($r['colacion']??0)-(int)($r['movilizacion']??0)),(int)($r['other']??0)]);$e=['base_salary'=>$base,'gratification_type'=>'Garantizada','health_institution'=>$r['health_institution'],'isapre_plan_uf'=>$isapre?$health/$params['uf']:0,'afp'=>$r['afp'],'meal_allowance'=>(int)($r['colacion']??0),'transport_allowance'=>(int)($r['movilizacion']??0),'family_loads'=>0,'mutual_rate'=>.009,'contract_type'=>'Plazo Fijo','contributes_afp'=>1];$v=['medical_leave_days'=>0,'unpaid_leave_days'=>0,'overtime_50'=>$hours,'overtime_100'=>0,'taxable_bonus'=>max(0,(int)($r['taxable']??0)-$base-(int)round($hours*$base/182*1.5)-(int)($r['grat']??0)),'commissions'=>0,'guaranteed_gratification'=>(int)($r['grat']??0),'non_taxable_bonus'=>max(0,(int)($r['nonTax']??0)-(int)($r['colacion']??0)-(int)($r['movilizacion']??0)),'advance'=>0,'company_loan'=>(int)($r['other']??0),'ccaf_loan'=>0,'other_discounts'=>0];$result=$calc->calculate($e,$v,$params);$slip->execute([$periodId,$eid,json_encode($result,JSON_UNESCAPED_UNICODE)]);}
    $pdo->commit();echo "Importados ".count($items)." trabajadores en empresa $company, periodo 2026-07\n";
} catch(Throwable $e){$pdo->rollBack();fwrite(STDERR,'ERROR: '.$e->getMessage().PHP_EOL);exit(1);}
