<?php
declare(strict_types=1);
require_once __DIR__.'/../app/Database.php';
function pdfStrings(string $file): array {$bytes=file_get_contents($file);if($bytes===false)throw new RuntimeException("No se pudo leer $file");$pages=[];$pos=0;while(($filter=strpos($bytes,'/Filter/FlateDecode',$pos))!==false){$stream=strpos($bytes,"stream\n",$filter);if($stream===false)break;$start=$stream+7;$end=strpos($bytes,'endstream',$start);if($end===false)break;$pos=$end+9;$raw=substr($bytes,$start,$end-$start);if(str_starts_with($raw,"\r"))$raw=substr($raw,1);$decoded=@gzuncompress($raw);if($decoded===false)$decoded=@gzinflate(substr($raw,2));if($decoded===false)continue;preg_match_all('/\(((?:\\.|[^)])*)\)\s*Tj/s',$decoded,$m);$page=[];foreach($m[1] as $v){$v=str_replace(['\\(', '\\)', '\\\\',"\\n","\\r"],['(',')','\\',' ',' '],$v);$page[]=trim($v);}if($page)$pages[]=$page;}return $pages;}
function money(?string $v): ?int {if($v===null||!preg_match('/^-?[0-9][0-9.]*$/',trim($v)))return null;return (int)str_replace('.','',trim($v));}
function rutKey(string $v): string{return strtoupper(preg_replace('/[^0-9Kk]/','',$v));}
function nextValue(array $t,string $label,int $from=0): ?int {foreach($t as $i=>$x){if($i<$from||stripos($x,$label)===false)continue;for($j=$i+1;$j<count($t)&&$j<=$i+4;$j++)if(($n=money($t[$j]))!==null)return $n;}return null;}
function liquidationRows(string $file): array {$rows=[];foreach(pdfStrings($file) as $tokens){$idx=null;$rut='';foreach($tokens as $i=>$token){if(preg_match('/\d{1,3}(?:\.\d{3})+-[0-9Kk]/',$token,$m)&&rutKey($m[0])!=='762712776'){$rut=$m[0];$idx=$i;break;}}if(!$rut)continue;$row=['rut'=>$rut,'name'=>$tokens[$idx+1]??''];foreach(['Sueldo base'=>'sueldo_base','HORAS EXTRA 50%'=>'horas_extra_50','HORAS EXTRA 100%'=>'horas_extra_100','GRATIFICACION LEGAL'=>'gratificacion','TOTAL IMPONIBLE'=>'total_imponible','VIATICOS'=>'viaticos','MOVILIZACION'=>'movilizacion','COLACION'=>'colacion','ASIGNACION FAMILIAR'=>'asignacion_familiar','TOTAL NO IMPONIBLE'=>'total_no_imponible','PREVISION'=>'prevision','SALUD'=>'salud','IMPUESTO UNICO'=>'impuesto_unico','SEGURO CESANTIA'=>'seguro_cesantia','TOTAL DESC. LEGALES'=>'total_descuentos_legales','ANTICIPO DE LIQUIDACION'=>'anticipo','TOTAL OTROS DESC.'=>'total_otros_descuentos','TOTAL HABERES:'=>'total_haberes','TOTAL DESCUENTOS:'=>'total_descuentos','ALCANCE LIQUIDO:'=>'liquido'] as $label=>$key)$row[$key]=nextValue($tokens,$label,$idx);$row['total_descuentos']=(int)($row['total_descuentos_legales']??0)+(int)($row['total_otros_descuentos']??0);$rows[]=$row;}return $rows;}
function bookTotals(string $file): array {$totals=[];foreach(pdfStrings($file) as $tokens){$idx=array_search('TOTAL GENERAL',$tokens,true);if($idx===false)continue;$nums=[];for($i=$idx+1;$i<count($tokens)&&count($nums)<12;$i++)if(($n=money($tokens[$i]))!==null)$nums[]=$n;if(count($nums)>=10)$totals[]=$nums;}return $totals;}
$rawIndex=array_search('RAW',$argv,true);if($rawIndex!==false){$file=$argv[$rawIndex+1]??'';$page=(int)($argv[$rawIndex+2]??0);echo json_encode(pdfStrings($file)[$page]??[],JSON_UNESCAPED_UNICODE|JSON_INVALID_UTF8_SUBSTITUTE|JSON_PRETTY_PRINT).PHP_EOL;exit;}
$liquidations=$argv[1]??'';$book=$argv[2]??'';$period='2026-07';$noDb=in_array('--no-db',$argv,true);if(!$liquidations||!is_file($liquidations)||!$book||!is_file($book)){fwrite(STDERR,"Uso: php tools/validate_external.php <LIQUIDACIONES JULIO.pdf> <libro de rem. junio 2026.pdf> [--no-db]\n");exit(2);}
$external=liquidationRows($liquidations);$bookTotals=bookTotals($book);$company=null;$actual=[];$companyRut='76271277-6';if(!$noDb){$pdo=Database::connection();$s=$pdo->prepare('SELECT * FROM companies WHERE REPLACE(REPLACE(UPPER(rut),".",""),"-","")=?');$s->execute([rutKey($companyRut)]);$company=$s->fetch();}
if($company){$s=$pdo->prepare('SELECT e.rut,p.calculation_json FROM employees e LEFT JOIN payroll_periods pp ON pp.company_id=e.company_id AND pp.period=? LEFT JOIN payslips p ON p.employee_id=e.id AND p.period_id=pp.id WHERE e.company_id=?');$s->execute([$period,$company['id']]);foreach($s as $row)$actual[rutKey($row['rut'])]=['calc'=>$row['calculation_json']?json_decode($row['calculation_json'],true):null];}
$csv=[['Periodo','RUT','Trabajador','Concepto','Externo','Aplicacion','Diferencia','Diagnostico']];$compared=0;$matches=0;$differences=0;$missing=0;foreach($external as $row){$item=$actual[rutKey($row['rut'])]??null;if(!$item){$missing++;$csv[]=[$period,$row['rut'],$row['name'],'TRABAJADOR','','','','No existe en la base local'];continue;}$calc=$item['calc']??[];$calc['external_nonTax']=(int)($calc['meal']??0)+(int)($calc['transport']??0)+(int)($calc['family']??0)+(int)($calc['nonTax']??0);$calc['external_discounts']=(int)($row['total_descuentos_legales']??0)+(int)($row['total_otros_descuentos']??0);$map=['sueldo_base'=>'sb','gratificacion'=>'grat','total_imponible'=>'taxable','total_no_imponible'=>'external_nonTax','total_haberes'=>'haberes','total_descuentos'=>'external_discounts','liquido'=>'net'];foreach($map as $label=>$key){if($row[$label]===null)continue;$ext=(int)$row[$label];$app=array_key_exists($key,$calc)?(int)$calc[$key]:null;$diff=$app===null?null:$app-$ext;$ok=$diff!==null&&abs($diff)<=1;$compared++;if($ok)$matches++;else$differences++;$csv[]=[$period,$row['rut'],$row['name'],$label,$ext,$app,$diff,$ok?'Coincide':'Revisar datos, variables, parametros o formula'];}}
$bookExpected=[];if(isset($bookTotals[0]))$bookExpected=['total_imponible'=>$bookTotals[0][5]??null,'total_no_imponible'=>$bookTotals[0][8]??null,'total_haberes'=>$bookTotals[0][9]??null];if(isset($bookTotals[1]))$bookExpected+=['total_descuentos_legales'=>$bookTotals[1][6]??null,'total_descuentos'=>$bookTotals[1][8]??null,'liquido'=>$bookTotals[1][9]??null];$bookActual=[];if($company){$s=$pdo->prepare('SELECT p.calculation_json FROM payslips p JOIN payroll_periods pp ON pp.id=p.period_id WHERE pp.company_id=? AND pp.period=?');$s->execute([$company['id'],'2026-06']);foreach($s as $r){$c=json_decode((string)$r['calculation_json'],true)?:[];foreach(['total_imponible'=>'taxable','total_haberes'=>'haberes','liquido'=>'net'] as $d=>$src)$bookActual[$d]=($bookActual[$d]??0)+(int)($c[$src]??0);$bookActual['total_no_imponible']=($bookActual['total_no_imponible']??0)+(int)($c['meal']??0)+(int)($c['transport']??0)+(int)($c['family']??0)+(int)($c['nonTax']??0);$bookActual['total_descuentos']=($bookActual['total_descuentos']??0)+(int)($c['discounts']??0);$bookActual['total_descuentos_legales']=($bookActual['total_descuentos_legales']??0)+(int)($c['afp']??0)+(int)($c['health']??0)+(int)($c['iusc']??0)+(int)($c['scWorker']??0);}}
$out=__DIR__.'/external_validation_'.date('Ymd_His').'.csv';$fp=fopen($out,'wb');foreach($csv as $line)fputcsv($fp,$line,';');fclose($fp);echo "Validacion externa\nEmpresa: ".($company['name']??'No encontrada')." ($companyRut)\nLiquidaciones: ".count($external)." trabajadores externos\nComparaciones: $compared | Coinciden: $matches | Diferencias: $differences | No encontrados: $missing\nTotales generales libro junio detectados: ".count($bookTotals)."\n";foreach($bookExpected as $key=>$value){$av=$bookActual[$key]??null;$diff=$av===null||$value===null?'n/d':(string)($av-$value);echo "Libro junio $key: externo=".($value??'n/d')." aplicacion=".($av??'n/d')." diferencia=$diff\n";}echo "Modo: ".($noDb?'extraccion sin base de datos':'comparacion con base de datos')."\nInforme: $out\n";
